domain: agendas
anchor: 2938f9af
files:
  - cmd/dcrdata/internal/api/apiroutes.go
  - cmd/dcrdata/internal/explorer/explorerroutes.go
  - cmd/dcrdata/public/js/charts/definitions/agenda.js
  - cmd/dcrdata/public/js/controllers/agenda_controller.js
  - cmd/dcrdata/public/js/controllers/agendas_controller.js
  - cmd/dcrdata/views/agenda.tmpl
  - cmd/dcrdata/views/agendas.tmpl
  - cmd/dcrdata/views/extras.tmpl
  - cmd/dcrdata/views/tx.tmpl
  - db/dbtypes/types.go
  - db/dcrpg/pgblockchain.go
  - db/dcrpg/queries.go
  - gov/agendas/deployments.go
  - gov/agendas/tracker.go
