domain: time-based-blocks
anchor: d12ec80f
files:
  - cmd/dcrdata/internal/explorer/explorer.go
  - cmd/dcrdata/internal/explorer/explorerroutes.go
  - cmd/dcrdata/main.go
  - cmd/dcrdata/views/timelisting.tmpl
  - db/dbtypes/conversion.go
  - db/dbtypes/types.go
  - db/dcrpg/internal/blockstmts.go
  - db/dcrpg/pgblockchain.go
  - db/dcrpg/queries.go
