domain: websocket
anchor: d12ec80f
files:
  - cmd/dcrdata/internal/explorer/explorerroutes.go
  - cmd/dcrdata/internal/explorer/websocket.go
  - cmd/dcrdata/internal/explorer/websockethandlers.go
  - cmd/dcrdata/main.go
  - cmd/dcrdata/public/index.js
  - cmd/dcrdata/public/js/services/messagesocket_service.js
  - pubsub/pubsubhub.go
  - pubsub/types/pubsub_types.go
  - pubsub/websocket.go
