domain: mempool
anchor: d12ec80f
files:
  - cmd/dcrdata/internal/explorer/explorer.go
  - cmd/dcrdata/internal/explorer/websockethandlers.go
  - cmd/dcrdata/public/js/controllers/homepage_controller.js
  - cmd/dcrdata/public/js/helpers/indicator_fill.js
  - cmd/dcrdata/views/home_mempool.tmpl
  - cmd/dcrdata/views/mempool.tmpl
  - explorer/types/explorertypes.go
  - mempool/collector.go
  - mempool/mempoolcache.go
  - mempool/monitor.go
  - pubsub/pubsubhub.go
