domain: decodetx
anchor: 45fa8e5c
files:
  - cmd/dcrdata/internal/api/insight/apiroutes.go
  - cmd/dcrdata/internal/explorer/explorer.go
  - cmd/dcrdata/internal/explorer/explorerroutes.go
  - cmd/dcrdata/internal/explorer/websockethandlers.go
  - cmd/dcrdata/public/js/controllers/rawtx_controller.js
  - cmd/dcrdata/public/js/services/messagesocket_service.js
  - cmd/dcrdata/views/rawtx.tmpl
  - db/dcrpg/insightapi.go
  - db/dcrpg/pgblockchain.go
  - pubsub/pubsubhub.go
  - pubsub/types/pubsub_types.go
