domain: visualblocks
anchor: d12ec80f
files:
  - cmd/dcrdata/internal/explorer/explorer.go
  - cmd/dcrdata/internal/explorer/explorerroutes.go
  - cmd/dcrdata/internal/explorer/templates.go
  - cmd/dcrdata/internal/explorer/websockethandlers.go
  - cmd/dcrdata/main.go
  - cmd/dcrdata/public/index.js
  - cmd/dcrdata/public/js/controllers/visualBlocks_controller.js
  - cmd/dcrdata/public/js/controllers/visualBlocks_controller.test.js
  - cmd/dcrdata/views/visualblocks.tmpl
  - db/dcrpg/pgblockchain.go
  - explorer/types/explorertypes.go
  - explorer/types/remaining.go
  - pubsub/pubsubhub.go
