domain: parameters
anchor: d12ec80f
files:
  - blockdata/blockdata.go
  - cmd/dcrdata/internal/explorer/explorer.go
  - cmd/dcrdata/internal/explorer/explorermiddleware.go
  - cmd/dcrdata/internal/explorer/explorerroutes.go
  - cmd/dcrdata/internal/explorer/parameters.go
  - cmd/dcrdata/main.go
  - cmd/dcrdata/views/parameters.tmpl
  - db/dcrpg/pgblockchain.go
  - explorer/types/explorertypes.go
